---

- name: install apache with mod_ssl
  yum:
    name:  mod_ssl
    state: latest

- name: send over conf
  template:
    src:  templates/{{ item }}.j2
    dest: /etc/httpd/conf/{{ item }}
  with_items:
    - httpd.conf

- name: template over conf.d
  template:
    src:  templates/{{ item }}.j2
    dest: /etc/httpd/conf.d/{{ item }}
  with_items:
    - ssl.conf

- name: send over modules
  template:
    src:  templates/{{ item }}.j2
    dest: /etc/httpd/conf.modules.d/{{ item }}
  with_items:
    - 00-base.conf
    - 00-mpm.conf
    - 00-proxy.conf
    - 01-weblogic-managed.conf

- name: clear some modules (not wanted here)
  file:
    path:  /etc/httpd/conf.modules.d/{{ item }}
    state: absent
  with_items:
    - 00-lua.conf
    - 00-dav.conf

