---

- name: install apache with mod_ssl
  yum:
    name:  mod_ssl
    state: latest

- include: libs.yml
- include: wallet.yml
- include: httpd-common.yml

- name: set service running
  service:
    name:    httpd
    enabled: yes
    state:   restarted
